apiVersion: apps/v1
kind: Deployment
metadata:
  name: slsa-simulation-app
  namespace: slsa-simulation
  labels:
    app: slsa-simulation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slsa-simulation-app
  template:
    metadata:
      labels:
        app: slsa-simulation-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: web
        image: ghcr.io/slsa-lab-blue/application:sha-1373d90dfb45f5b1f2e45093eb367011915a322a
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
